### ISSUE TITLE
Build latest runtime

### ISSUE THREAD

**Issue by ImperatorS79** [PhoenicisOrg/phoenicis-winebuild#102]
@qparis Could you rebuild the latest runtime for Linux so that libfreetype, libbsd and libudev are included ?

**Comment by ImperatorS79** [comment]
Runtimes are still not up to date (libasound is missing as well as krb related libs); despite the date being September 2019.

**Comment by qparis** [comment]
Can you retry?

**Comment by ImperatorS79** [comment]
I still have a bunch if lib to add to the runtime and typo to fix related to krb5 ^^.

**Comment by qparis** [comment]
Is it still valid?
