### ISSUE TITLE
Add some tools to display build progressbar

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis-winebuild#11]
I do not get any output after `Successfully tagged phoenicis/winebuild/linux-x86:wine` and do not see a log file.

**Comment by qparis** [comment]
Interactive builder stores logs in dist/

**Comment by plata** [comment]
Just figured that out as well. I think the interactive builder should write the log to the console as well. It's a bit confusing right now because you do not see anything happening.

**Comment by plata** [comment]
Btw: Is dist cleared when you start a new build? If not, what happens to the build result and logs if you build the same version twice?

**Comment by qparis** [comment]
It should be possible, however I would rather see a progress bar

**Comment by qparis** [comment]
dist is not cleared. File are overwritten I guess

**Comment by plata** [comment]
If the Wine build allows a progress bar, that would be nice. I'm just not sure if it does (e.g. with CMake it would be easy).

**Comment by qparis** [comment]
We can use the size of the log file to guess the progression state

**Comment by plata** [comment]
That can either work quite well or horribly bad. I think the first step should be to just show the output such that it's clear that something's still going on.

**Comment by qparis** [comment]
We used this system on POLv4, it worked very great

**Comment by plata** [comment]
Ok. Fine for me then.

**Comment by qparis** [comment]
Done for the environment generation part: web services are able to give a percentage update on the creation of a build environement.
The same work needs to be done for the wine building process itself

**Comment by qparis** [comment]
Done
