### ISSUE TITLE
Wine amd64 4.16, 4.17 and 4.18 missing

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis-winebuild#110]

**Comment by Gcenx** [comment]
For macOS build from Wine-4.17, Wine-4.16 required an additional patch.

**Comment by plata** [comment]
Can it happen that the Linux builds are missing because the macOS builds do not work?

**Comment by qparis** [comment]
Should not be no

**Comment by plata** [comment]
So what's the issue?

**Comment by Gcenx** [comment]
Is it only the 64Bit that’s have failed on Linux?

As I see the 32Bit builds for staging anyway

**Comment by plata** [comment]
Yes, only 64bit.

**Comment by Gcenx** [comment]
I’ve seen a lot of upstream changes related to unwind try adding --without-unwind it configure for wine64 build that will lightly fix the issue.

**Comment by plata** [comment]
Should this be added in general or only for certain versions?

**Comment by Gcenx** [comment]
For select versions would be preferable but for now just check if that really resolved the issue, luckily configure will ignore unknown commands without failing so leaving it in won’t cause any harm if a per-version selection system isn’t implemented.

Freetype is an issue anyway also wine versions below 2.18 can’t be built with the current versions of freetype, it would require a freetype version below 2.8.1 or make a patch for all lower versions to accept freetype 2.8.1+

**Comment by plata** [comment]
@qparis can you try that?

**Comment by qparis** [comment]
Yep, will try it this week end

**Comment by qparis** [comment]
configure: error: Cannot build a 32-bit program, you need to install 32-bit development libraries

Seems that some change has been made to phoenicis-winebuild that were not tested..

**Comment by Gcenx** [comment]
What builder/script was having this issue?

**Comment by qparis** [comment]
Linux amd64

**Comment by plata** [comment]
Should we have Travis for PRs for winebuild?

**Comment by qparis** [comment]
Ideally yes, we should check that we are able to build wine

**Comment by plata** [comment]
I'm don't really know how winebuild works but maybe it's sufficient to build the latest Wine version for representative systems (OSX/Linux 32/64bit)?

**Comment by Gcenx** [comment]
@qparis I have a feeling something changed/broke within docker.

Last night I decided to clean up the Darwin environment and decided on making clang/gcc wrappers within the environment, they failed to function.

So I’m thinking the same could also true for the install_32bits_dependencies.sh

**Comment by qparis** [comment]
It is quite unlikely that the problems comes from docker. Have you built an environment from scratch?

**Comment by Gcenx** [comment]
> It is quite unlikely that the problems comes from docker. Have you built an environment from scratch?

@qparis 
Yes I had wiped the docker image and ensured it was updated, I can work around the issue in another way but check my above comment I made an edit you might find useful

**Comment by qparis** [comment]
Ok, where is the error you are encountering?

**Comment by Gcenx** [comment]
I copied the idea from install_32bits_dependencies.sh
And just altered the example from wine-packing. So ncurses configure launches and shows the wrappers contents then exits.
Then I took the example we used within the builder to make the wrapper before compiling wine/wine64 same thing crashed out.

(I had already removed unneeded items from ncurses 32Bit compile to allow the wrapper to function)

When I’m home later I’ll try making the wrapper inside the builder and see if it then works

**Comment by qparis** [comment]
Yep, but are you able to build the environment?

**Comment by Gcenx** [comment]
If I remove the clang/gcc wrappers and use custom exports mapped to CC yes, with the wrapper containing the same information no.

**Comment by qparis** [comment]
The clang/gcc wrapper?

**Comment by Gcenx** [comment]
Within the builder we create a gcc wrappers for compiling wine, I decided to move those into the Environment instead to make maintenance simpler.

The same wrappers that function within the builder don’t function within the environment creation.

**Comment by qparis** [comment]
What line of code are you refering exactly?

**Comment by Gcenx** [comment]
#### 64bits
export CC="clang-7 -O3 -target x86_64-apple-darwin17 -mlinker-version=0.0 -mmacosx-version-min=10.8 -B/root/osxcross/target/bin/ -isysroot/root/osxcross/target/SDK/MacOSX$FRAMEWORK.sdk/  -F/root/osxcross/target/macports/pkgs/opt/local/Library/Frameworks -Wno-unused-command-line-argument -Wno-deprecated-declarations"

## This hack will allow winegcc to use the right compiler
echo '$CC "$@"' > "/root/osxcross/target/bin/x86_64-apple-darwin17-gcc"
chmod +x "/root/osxcross/target/bin/x86_64-apple-darwin17-gcc"

But appended RUN as needed, the wrapper gets made but didn’t function.

**Comment by qparis** [comment]
This is not really surprising. I'm not sure that pipes and env variable work like this with Dockerfiles.

**Comment by qparis** [comment]
The best would be to use the command "COPY" to create the file

**Comment by Gcenx** [comment]
The reason I’d mentioned this is because I’d also created the wrapper using the example from wine-packing but done the way install_32bits_dependencies.sh was created.

So I believe it’s related for some reason install_32bits_dependencies.sh isn’t being created correctly causing the missing dev files for wine32 for Linux

**Comment by qparis** [comment]
Ok, so it must come from a recent change

**Comment by qparis** [comment]
The following packages have unmet dependencies:
 libcups2-dev:i386 : Depends: libcupsimage2-dev:i386 (= 2.2.1-8+deb9u4) but it is not going to be installed

**Comment by qparis** [comment]
Seems to be fixed
