### ISSUE TITLE
[Linux] Wine 5.20-staging some functions missing

### ISSUE THREAD

**Issue by keybreak** [PhoenicisOrg/phoenicis-winebuild#133]
![image](https://user-images.githubusercontent.com/47599989/97541799-ce505900-19d6-11eb-8cd7-83698fae1a73.png)

No VAAPI or GTK3 theming, is this upstream or phoenics-winebuild?

**Comment by plata** [comment]
I'm not aware of anything on our side which could cause this.

**Comment by ImperatorS79** [comment]
The problems certainly comes from missing libs (lbvaapi, gtk3,...) while building.

**Comment by ImperatorS79** [comment]
Okay, I have checked and there are no problem with such libs on winebuild.
