### ISSUE TITLE
Local source builds fail macOS

### ISSUE THREAD

**Issue by Gcenx** [PhoenicisOrg/phoenicis-winebuild#144]
Didn’t get chance to open this before needing to head out for work.

I’ve tested this with amd64 and x86, these both seem to fail on the 32Bit built something with mingw-dlltool being unable to find a needed file? (it’s something like that)

The used source isn’t the problem as it complies without issue on my local build system but fails here, not sure what the issue could be exactly unfortunately.

**Comment by qparis** [comment]
Can you copy and paste the log?

**Comment by Gcenx** [comment]
I don’t have remote access to my system, I’ll copy/paste the output once I’m home.

**Comment by Gcenx** [comment]
Here is the output;
```
/root/wine-tools/tools/winebuild/winebuild -b i686-w64-mingw32 -w --implib -o dlls/msvcr100/libmsvcr100.cross.a --export \
  dlls/msvcr100/msvcr100.spec dlls/msvcr100/iob.cross.o dlls/msvcr100/mathf.cross.o \
  dlls/msvcr100/onexit.cross.o
/root/wine-tools/tools/winebuild/winebuild -b i686-w64-mingw32 -w --implib -o dlls/msvcr110/libmsvcr110.cross.a --export \
  dlls/msvcr110/msvcr110.spec dlls/msvcr110/iob.cross.o dlls/msvcr110/mathf.cross.o \
  dlls/msvcr110/onexit.cross.o
/root/wine-tools/tools/winebuild/winebuild -b i686-w64-mingw32 -w --implib -o dlls/msvcr120/libmsvcr120.cross.a --export \
  dlls/msvcr120/msvcr120.spec dlls/msvcr120/iob.cross.o dlls/msvcr120/mathf.cross.o \
  dlls/msvcr120/onexit.cross.o
/usr/bin/i686-w64-mingw32-dlltool: bfd_open failed open stub file: dtvtbs01138.o: Input/output error
/usr/bin/i686-w64-mingw32-dlltool: bfd_open failed open stub file: djvtbs01217.o: Input/output error
winebuild: /usr/bin/i686-w64-mingw32-dlltool failed with status 1
winebuild: /usr/bin/i686-w64-mingw32-dlltool failed with status 1
make: *** [Makefile:86922: dlls/msvcr120/libmsvcr120.cross.a] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:85254: dlls/msvcr100/libmsvcr100.cross.a] Error 1
```

And yes these files it needs do not exist, if I use `interactive_builder.py` to build the same version I don't have any issues so this one seems really strange.

**Comment by qparis** [comment]
Input/output error seems more a general system related error.

Have you tried to reset your Docker settings?

**Comment by Gcenx** [comment]
Reset docker setting back to default no change, the same source when downloaded and built with `interactive_builder.py` doesn't fail but building the same source using the local source build support always ends up failing.

**Comment by qparis** [comment]
Yeah, because the interactive builder does not use local mount 

    container.with_mount({
        "src": wine_source,
        "dest": "/root/wine-git",
        "mode": "rw"
    })

Which seems to have a link with your I/O error

**Comment by Gcenx** [comment]
Maybe change the local source build feature to copy the sources into docker over mounting the source directory.

Since all the logging is directly displayed in the terminal session this shouldn’t be an issue.

**Comment by qparis** [comment]
The key idea or this feature is to be able to modify the source code while trying to recompile and accelerate patch creation, git bisecting, etc…

We could provide an extra flag like —copy instead of —mount

**Comment by Gcenx** [comment]
The issue seems to be when compiling the source it’s getting compiled in the mount point, so maybe just changing around the structure so the compile happens within docket instead of the mount point would be enough.

**Comment by qparis** [comment]
Yeah but sometimes you also want to access the intermediate files, like the generated makefile or other stuff to debug

**Comment by Gcenx** [comment]
Yes I was thinking that also, this one is going to be annoying to resolve if that’s even possible.

**Comment by qparis** [comment]
This seems to be more a problem with docker

**Comment by qparis** [comment]
Seems that wine32on64 does not work. When I run a 32bits programs, it says either 

00cc:err:process:exec_process L"Z:\\exec.exe" not supported on this system

or something like "This is not a 64bits prefix" 

Have i mess something up?

**Comment by Gcenx** [comment]
Just checked the CX21.0.0 build from here and yeah it refuses to launch any 32Bit binaries.

**Comment by qparis** [comment]
Have you tried to build it by yourself or have you tried POL's build?

**Comment by Gcenx** [comment]
I did a CX21 build the same day the sources landed and that works without issue.

The POM build has the issues you mentioned. Strange as I don’t see any reason why this would have happened.

**Comment by qparis** [comment]
Did you build it with Phoenicis winebuild?

**Comment by Gcenx** [comment]
No I didn’t use phoenicis-winebuild for my own WineCX21.0.0 build.

**Comment by qparis** [comment]
So the difference is either in the build process or in winecx source

**Comment by Gcenx** [comment]
Checking over the log and it looks to be similar to the previous issue. The 32on64 stage reads like a wine64 build just using the wine32on64 binary name, library install location.

If you search the log for `-mwine32` that flag isn’t being used, it’s instead `-m64`, so maybe more of those annoying cross_compiling checks need to be removed.

**Comment by qparis** [comment]
I see. I will try to fix the script

**Comment by Gcenx** [comment]
The altered patch looks to have resolved the issue with wine32on64. After the patch applied there is output complaining about white space.

I altered the build script to only do wine32on64 to speed things up, then tested on my M1 Mac Mini, it launched and allows me to run a 32Bit GOG installer.
