### ISSUE TITLE
The readme file should explain how to give permission to the current user to use docker on Linux

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis-winebuild#2]
`python3 ./example_linux.py`
gives
```
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.35/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=environments%2Flinux-x86-wine&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=9299bc1302fef86bf36220fe55229037514913d6bc28eed3be6175b12e88e911&shmsize=0&t=phoenicis%2Fwinebuild%2Flinux-x86%3Awine&target=&ulimits=null: dial unix /var/run/docker.sock: connect: permission denied
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.35/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.35/containers/kill?signal=KILL: dial unix /var/run/docker.sock: connect: permission denied
Container name cannot be empty
```

**Comment by qparis** [comment]
I see. Does your current user belongs to the docker group?

**Comment by plata** [comment]
It didn't. But now I've added it and still the same.

**Comment by qparis** [comment]
Can you try the command 
docker run hello-world

**Comment by plata** [comment]
```
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.35/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
```

**Comment by qparis** [comment]
Try to open a new command line window and/or logout / login. It should work

**Comment by plata** [comment]
It runs now.

**Comment by qparis** [comment]
Good. If this build works correctly, I’ll replace POL4 and POL5 system with this one, with two hosting mirrors

**Comment by qparis** [comment]
Do you think we should embed the libs as we do on MacOS X?

**Comment by plata** [comment]
I get `debconf: delaying package configuration, since apt-utils is not installed`. Not sure if it's important. What is supposed to happen in the run? Does it finish at any time and leave the built files somewhere? Right now it seems to be stuck at `Successfully tagged phoenicis/winebuild/linux-x86:wine`.

The build should be self contained if possible. That will also make it easier to use it in the flatpak.

**Comment by qparis** [comment]
The examplz you are running is redirecting the output inside a log file

**Comment by plata** [comment]
I see. I guess it would be better to write it to the console.

**Comment by plata** [comment]
We can add the missing runtime dependencies to the Phoenicis flatpak.
