### ISSUE TITLE
Support for transform feedback missing

### ISSUE THREAD

**Issue by Zemogiter** [PhoenicisOrg/phoenicis-winebuild#28]
Is there any chance someone could build wine 3.20 and wine 3.21 with transform feedback patch (
[winevulkan-transform-feedback.patch.txt](https://github.com/PhoenicisOrg/scripts/files/2663331/winevulkan-transform-feedback.patch.txt) ) applied then upload it to the server? I need it for my Space Engineers script (based on instructions at https://appdb.winehq.org/objectManager.php?sClass=version&iId=30180 ) but I can't get the patched wine to install.

**Comment by ImperatorS79** [comment]
Normally this patch is not needed anymore. Transform feedback should be merge in wine from wine 3.19. Wine must be build with at least vulkan 1.1.88 -> [https://github.com/doitsujin/dxvk/issues/695](https://github.com/doitsujin/dxvk/issues/695).

**Comment by Zemogiter** [comment]
I have an NVIDIA card with drivers version 415 (opensource)
