### ISSUE TITLE
[Idea] Rename amd64 to universal and use amd64 for 64bits-only compatible builds

### ISSUE THREAD

**Issue by qparis** [PhoenicisOrg/phoenicis-winebuild#3]
It seems that 32bits OS are becoming deprecated, especially on Mac. But we could imagine this to happen on linux one day. 

However, there are now some 64bits programs that can run on wine. It would be interesting to have builds that completely drop 32bits support so that they could support those operating system.

Therefore, it would make sense to adopt the following conventions: 

- x86 : 32bits-only builds
- amd64 : 64bits-only builds
- unviersal : Builds that can run 32bits and 64bits programs (On 64bits OSs)

@plata @madoar What do you think?

**Comment by plata** [comment]
Isn't there an official Wine naming scheme for this? Especially for the last point: isn't this what would normally be called "multiarch"?

**Comment by ImperatorS79** [comment]
I do not really see the interest of 64bits only builds since a lot of 64bits programs can use 32bits libs.

**Comment by madoar** [comment]
I'm fine with the conventions.

**Comment by ImperatorS79** [comment]
You could also use x86, x64, x86_64.

**Comment by qparis** [comment]
hm x86_64 means 64bits in terms of build target

**Comment by plata** [comment]
What exactly is the difference (technically) between x86_64 builds with support for 32bit apps and without?

**Comment by qparis** [comment]
Today, we have: 
* 32bits build (built with -m32 switch) : they can basically run on any OS that has a 32bits version of libc / other dependencies. They can only run 32bits software. Basically, we mainly rely on this one
* 64bits build : they can run on a 64bit OS and can theoritically run 32bits and 64bits programs. This kind of build contains in fact two versions of wine (a 32bits one and a 64bits one). 

We can also imagine to have a full 64bits build that can only run 64bits program.

**Comment by plata** [comment]
I understood that. But the 64bit builds is with `-m64` (implicitly). So how would the 64bit only builds work?

**Comment by qparis** [comment]
I don’t understand. The current 64bits build has two parts, one is built with -m32, the other one with -64
The full 64bits would only have the -64 parts 

You can have a look to the Darwin amd64 script for more details

**Comment by plata** [comment]
Ok. I got it now. One question though: what's the point of the "universal" build? Why not use x86 for 32bit prefixes and amd64 for 64bit prefixes?

**Comment by qparis** [comment]
Because you can run 32bit app on a 64bit prefix :-)

**Comment by plata** [comment]
And the 64bit Wine cannot do that?

**Comment by qparis** [comment]
Nope

**Comment by plata** [comment]
I see.

**Comment by qparis** [comment]
Better forget that for now and wait for winehq decision about 32bits/64bits support
