### ISSUE TITLE
Gecko/Mono versions

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis-winebuild#30]
E.g. wine 2.0-rc4 has
- wine_gecko-1.5-x86.msi
- wine-mono-0.0.4.msi

while 1.9.24 has
- wine_gecko-2.40-x86.msi
- wine-mono-4.5.6.msi

Moreover, the checksums and file names are missing.

**Comment by qparis** [comment]
Any way to get the right mono version from the wine version?

**Comment by ImperatorS79** [comment]
@qparis You should check [https://wiki.winehq.org/Mono](https://wiki.winehq.org/Mono) and [https://wiki.winehq.org/Gecko](https://wiki.winehq.org/Gecko)

**Comment by plata** [comment]
Check what I did for wine-sources: https://github.com/PhoenicisOrg/wine-sources/blob/master/winehq-macosx.py

**Comment by plata** [comment]
E.g. for Wine 5.0 no gecko/mono version is set at all.

**Comment by plata** [comment]
Nobody should need these old versions anymore. Open new issue if this is still a problem with recent versions.
