### ISSUE TITLE
Support of patch distributions

### ISSUE THREAD

**Issue by qparis** [PhoenicisOrg/phoenicis-winebuild#33]
The idea behing this ticket is to be able to extend a base distribution (upstream, staging, cx, proton when it's done) with a wine patchset.

**Comment by plata** [comment]
This will increase the number of builds. Maybe we should think about some mechanism to deprecate old builds?

**Comment by qparis** [comment]
These distribution will not necessarily build all wine builds. I think it will more be on demand

**Comment by plata** [comment]
Still it will maybe create many builds which might be relevant now but are completely obsolete in 2-3 years (like this 15.27-needforspeed).

**Comment by qparis** [comment]
Yes I agree. We need to have a system that looks for build usage maybe

**Comment by plata** [comment]
I will open a new issue for this.

**Comment by qparis** [comment]
Done
