### ISSUE TITLE
Support of CX distribution

### ISSUE THREAD

**Issue by qparis** [PhoenicisOrg/phoenicis-winebuild#34]

**Comment by qparis** [comment]
@plata

**Comment by plata** [comment]
If CX builds are available in binary, we can add them to wine-sources instead of building them again on our own.

**Comment by qparis** [comment]
I see some counter arguments: 

- I'm not sure they are available in binary. (Need to check though)
- The goal of phoenicis-winebuild is to provide to anyone a unified and simplified system to build any version of wine. We are the first consumer of this platform, but other people could 
- We can control supported OS version 
- We can later imagine create derivate distributions with patches

**Comment by plata** [comment]
I agree to all of your points. My concern is that a huge amount of available versions will fragment our ecosystem and potentially blow up the build servers.

So a big question for me is:
Do we want that all these distributions are available by default for writing scripts?

**Comment by qparis** [comment]
Concerning CX builds, I don't expect as many version as wine, so it should not be a problem. 

Regarding your point in general:
- I think we could optimize the build time by building builds in RAM
- I'm going to transfer (probably this afternoon) winebuild to a more powerful machine which will allow us to build fater. 
- The storage is not (yet) a problem

**Comment by plata** [comment]
Then I'm fine. Maybe one crazy thought: could it make sense to handle the Wine builds with a similar repository system like we have for the scripts? (Didn't really think about this myself in depth).

**Comment by Gcenx** [comment]
@qparis @plata 
WineCX binaries do exist for Wineskin and my [Wineskin Fork](https://github.com/Gcenx/WineskinServer) but you would end up with dependancies hell so better to build them yourself's so you are aware what dependancies would be needed.

> Then I'm fine. Maybe one crazy thought: could it make sense to handle the Wine builds with a similar repository system like we have for the scripts? (Didn't really think about this myself in depth).

I handle it that way myself now, I only have the WineCX builds for download anything else is just download and repackaged from Winehq. You lightly won't want to be repacking Winehq versions as this project is Linux/macOS not just macOS so you really need Vulkan Support for DXVK.

**Comment by qparis** [comment]
@Gcenx That makes sense. We need to test it because so far, I cannot run winecx directly from a terminal. I'm getting: 
`terminals database is inaccessible`

However, if I create a script that I run thanks to nohup, no problem

**Comment by Gcenx** [comment]
> @Gcenx That makes sense. We need to test it because so far, I cannot run winecx directly from a terminal. I'm getting:
> `terminals database is inaccessible`
> 
> However, if I create a script that I run thanks to nohup, no problem

`terminals database is inaccessible`

That's more of an OS issue on your end, I had that too before when I upgraded to Mojave after removing macports but forgot to fix my paths correctly.

When I have more time to really go over and test this build system I will check and see if I can help in any other way.

**Comment by qparis** [comment]
> > @Gcenx That makes sense. We need to test it because so far, I cannot run winecx directly from a terminal. I'm getting:
> > `terminals database is inaccessible`
> > However, if I create a script that I run thanks to nohup, no problem
> 
> `terminals database is inaccessible`
> 
> That's more of an OS issue on your end, I had that too before when I upgraded to Mojave after removing macports but forgot to fix my paths correctly.
> 
> When I have more time to really go over and test this build system I will check and see if I can help in any other way.

That would be awesome. Anyway, thank you for the help you've already given

**Comment by qparis** [comment]
@Gcenx if you are interested, we also have interesting patches that improve macOS integration when porting apps. For example, one of them allow to handle document opening directly through wine even if wine already opened.

**Comment by qparis** [comment]
Done
