### ISSUE TITLE
terminals database is inaccessible

### ISSUE THREAD

**Issue by qparis** [PhoenicisOrg/phoenicis-winebuild#40]
Since we are building wine with 10.11 SDK, I get the error 
`terminals database is inaccessible` 
When I execute it from a terminal. (No problem if I redirect the output with > however). 

* Can someone confirm the problem with the official builds?

**Comment by plata** [comment]
This is only for OSX, right?

**Comment by qparis** [comment]
You can find our builds here: https://www.playonlinux.com/wine/

**Comment by Gcenx** [comment]
> You can find our builds here: https://www.playonlinux.com/wine/

I will check the those but I did mean more the one you had issues with on your end.

**Comment by qparis** [comment]
For example this one: https://www.playonlinux.com/wine/binaries/phoenicis/upstream-darwin-x86/PlayOnLinux-wine-3.19-upstream-darwin-x86.tar.gz

**Comment by Gcenx** [comment]
> For example this one: https://www.playonlinux.com/wine/binaries/phoenicis/upstream-darwin-x86/PlayOnLinux-wine-3.19-upstream-darwin-x86.tar.gz

It works on my system from Terminal without issue
<img width="1263" alt="screen shot 2018-12-24 at 8 34 49 pm" src="https://user-images.githubusercontent.com/38226388/50408781-784b7280-07bb-11e9-975f-701da9ac8c03.png">

**Comment by qparis** [comment]
That’s good news.

Concerning Freetype, do you have exported DYLD_FALLBACK_LIBRARY_PATH and the two other variables as mentioned on read me?

**Comment by Gcenx** [comment]
> That’s good news.
> 
> Concerning Freetype, do you have exported DYLD_FALLBACK_LIBRARY_PATH and the two other variables as mentioned on read me?

I actually forgot to do that as usually I don't need to worry about that. But the paths are also wrong unless you install wine to /usr/bin

Wine by default "should" pickup the libs inside /lib and wine64 should pickup /lib64

**Comment by Gcenx** [comment]
> I guess it is just a compilation option, but it should work with the environement variable set. We might need to fix that but I'm not sure how important it is

I believe since it cross-compiled the rpath need to be fixed, that’s what the winehq builder does for the OSX builds.

But compared to my XCode compile where 64Bit Regedit crashes, the compiles from the  link you provided don’t have that issue 👍 


Guess I need to setup another Linux install so I can test and expand this more

**Comment by qparis** [comment]
You can also test this on macOS directly. All you need is to have Docker

**Comment by Gcenx** [comment]
> You can also test this on macOS directly. All you need is to have Docker

My MacBook Pro takes forever to compile the needed ports normally, I guess if I first make some changes to how macports is handles ports first maybe I can speed that up.
As the quick look over the environment shows your only installing the basic requirements for compiling wine

**Comment by qparis** [comment]
If you use phoenicis-winebuild, this will be handled completely differently and macport will no longer be used. The advantage also is that you are sure that your system is not biased when you try to run the build to see if they work

**Comment by qparis** [comment]
Feel free to do so

**Comment by qparis** [comment]
Closing this issue since it does not seem to be a winebuild problem

**Comment by qparis** [comment]
After even more investigation, the bundled ncurses looks for /opt/local/share/terminfo

We can overide this by setting export TERMINFO="/usr/share/terminfo/"

**Comment by qparis** [comment]
Last commit should fix this problem
