### ISSUE TITLE
How to setup and use the project on macOS?

### ISSUE THREAD

**Issue by Gcenx** [PhoenicisOrg/phoenicis-winebuild#48]
I'm still relatively new to docker style projects.

I have

- Installed Docker.app
- Python3 via homebrew
- pip installed within Python3
- pip install docker
- pip install docker-py

I changed to the folder that I downloaded the project from and launched
`PYTHONPATH="$PWD" python examples/interactive_builder.py`

But I get the following errors
`Traceback (most recent call last):
  File "examples/interactive_builder.py", line 3, in <module>
    from packagers.PhoenicisWinePackageCreator import PhoenicisWinePackageCreator
  File "/Users/gcenx/Documents/GitHub/phoenicis-winebuild/packagers/PhoenicisWinePackageCreator.py", line 1, in <module>
    import pathlib
ImportError: No module named pathlib`

I'm sure I'm not doing something correctly here but I'm not sure what?

I would much rather get up and running on my side before suggesting additional changes

**Comment by qparis** [comment]
What does python —version return?

**Comment by qparis** [comment]
In fact this is not really a typical docker project. It is a project that uses docker but it is not deployed with Docker

**Comment by Gcenx** [comment]
> What does python —version return?

2.7, I should have used python3

`Traceback (most recent call last):
  File "examples/interactive_builder.py", line 3, in <module>
    from packagers.PhoenicisWinePackageCreator import PhoenicisWinePackageCreator
  File "/Users/gcenx/Documents/GitHub/phoenicis-winebuild/packagers/PhoenicisWinePackageCreator.py", line 3, in <module>
    from builders.WineBuilder import WineBuilder
  File "/Users/gcenx/Documents/GitHub/phoenicis-winebuild/builders/WineBuilder.py", line 3, in <module>
    from core.Container import Container
  File "/Users/gcenx/Documents/GitHub/phoenicis-winebuild/core/Container.py", line 5, in <module>
    from core.DockerClient import DockerClient
  File "/Users/gcenx/Documents/GitHub/phoenicis-winebuild/core/DockerClient.py", line 1, in <module>
    import docker
ModuleNotFoundError: No module named 'docker'`

> In fact this is not really a typical docker project. It is a project that uses docker but it is not deployed with Docker

Yeah I noticed but I'm still new to using Docker anyway, that's why I wondered if it would be simpler to just use a Linux system

**Comment by plata** [comment]
Or we dockerize the docker usage XD

**Comment by qparis** [comment]
Don’t worry, it is pretty straightforward to set up the project. Just ensure that you run it with python > 3.6 and it should be fine

**Comment by Gcenx** [comment]
> Don’t worry, it is pretty straightforward to set up the project. Just ensure that you run it with python > 3.6 and it should be fine

Maybe I'm missing some sets to setting it up then?
`python3 --version
Python 3.7.2`

The error I got from using python3 was;
`Traceback (most recent call last): File "examples/interactive_builder.py", line 3, in <module> from packagers.PhoenicisWinePackageCreator import PhoenicisWinePackageCreator File "/Users/gcenx/Documents/GitHub/phoenicis-winebuild/packagers/PhoenicisWinePackageCreator.py", line 3, in <module> from builders.WineBuilder import WineBuilder File "/Users/gcenx/Documents/GitHub/phoenicis-winebuild/builders/WineBuilder.py", line 3, in <module> from core.Container import Container File "/Users/gcenx/Documents/GitHub/phoenicis-winebuild/core/Container.py", line 5, in <module> from core.DockerClient import DockerClient File "/Users/gcenx/Documents/GitHub/phoenicis-winebuild/core/DockerClient.py", line 1, in <module> import docker ModuleNotFoundError: No module named 'docker'`


I removed homebrew and anything else then clean installed homebrew as I mentioned above so nothing would interfere with this.

**Comment by qparis** [comment]
Ok! The problem is that you have installed pip with python2

Do you have a pip3, or a pip3.7 command?

**Comment by Gcenx** [comment]
> Ok! The problem is that you have installed pip with python2
> 
> Do you have a pip3, or a pip3.7 command?

brew thinks I have pip installed but now its not working....

would it be possible to run this on the system python or does it really need python3?

**Comment by qparis** [comment]
It needs python3 unfortunately. 
Try python3.6 -m pip install docker

**Comment by qparis** [comment]
If it does not work, you can try python3.6 -m ensurepip

**Comment by Gcenx** [comment]
> If it does not work, you can try python3.6 -m ensurepip

I had to do the above first

> It needs python3 unfortunately.
> Try python3.6 -m pip install docker

Then I did that, now I'm greeted with a list of wine versions, seems to be doing something now.

I'm gonna keep this open for the moment just incase

**Comment by qparis** [comment]
Cool! I hope the interactive builder still works. If it is not the case, I'll update it for you

**Comment by qparis** [comment]
Can we close this issue?
