### ISSUE TITLE
macOS make dylib bundling optional

### ISSUE THREAD

**Issue by Gcenx** [PhoenicisOrg/phoenicis-winebuild#49]
I think as you want to save disk space that should be optional, but when selected the should be bundled as needed so 32bit would only have 32bit but 64bit would bundle phat dylibs within /lib then symlink them into /lib64 that would also remove the need for the fallback env.

Also could an option be added to just build/bundle the dylibs only?
I know it seems weird but it could be useful for updating only the dylibs, that wouldn't need to bother with the /lib64 symlink from /lib.

I have not looked over POM but I'm assuming you only use a set of dylibs from within the app not replying on the dylibs that are bundled from winebuild?

**Comment by qparis** [comment]
> I think as you want to save disk space that should be optional, but when selected the should be bundled as needed so 32bit would only have 32bit but 64bit would bundle phat dylibs within /lib then symlink them into /lib64 that would also remove the need for the fallback env.

For this one, it would be pretty simple to do. 
Ideally, we just have to create a BundleDependenciesLibrairiesHook implementing AbstractHook interface.
This hook would bundle the libs and fixes the imports. 
Then we can create a slim disitribution like upstream or staging that does not execute this hook


> Also could an option be added to just build/bundle the dylibs only?
> I know it seems weird but it could be useful for updating only the dylibs, that wouldn't need to bother with the /lib64 symlink from /lib.
Little bit harder with this architecture, but not impossible. At the end, what you just need to have is a builder script that does not build anything. 

> I have not looked over POM but I'm assuming you only use a set of dylibs from within the app not replying on the dylibs that are bundled from winebuild?
POM is really a mess at the moment. The dependencies used to be within the apps, but at the end, it causes problems because their version change from the differents wineversions. 
So now, we're trying standalone builds and see if it causes less problems for the users

**Comment by qparis** [comment]
Now that runtime are supported, can we safely remove the dependencies from the binaries?

**Comment by Gcenx** [comment]
> Now that runtime are supported, can we safely remove the dependencies from the binaries?

@qparis  yes it requires some changes, due to another bug introduced in with the need of mingw for PE files.
We can't patch the .so files anymore or they will break unless the runtime is bundled.....

I only discovered this later yesterday but IRL made me forget, I confirmed that's the case as when I patched the .so files winecfg has the drive mount error again. But skipping patching the .so files it worked correctly when using dylib fallback variable.

The other thing is the runtime scripts also need some modifications, the 64bit version doesn't currently include VKD3D due to it needing wine-tool64 to build

**Comment by qparis** [comment]
Ok, for your first point, what do you mean by "patch". Are you talking about the relinking process? 

For the second point, it should be pretty straightforward

**Comment by Gcenx** [comment]
> Ok, for your first point, what do you mean by "patch". Are you talking about the relinking process (fix imports)?
> 
> For the second point, it should be pretty straightforward

Yes need to remove the .so sections from fix imports.

Yes I wanted to wait until you were done with the recent Hangover commits but I'm away from my computer for the moment.

Side Note;
wine-4.8 **_can_** be used but macDriver would need to manually set, that was fixed in wine-4.9 by setting the default of mac,x11. Something I'm already doing by default anyway.

**Comment by qparis** [comment]
I think we'd better run the file command on the .so file to detect if needs to be fixed or not

**Comment by Gcenx** [comment]
> I think we'd better run the file command on the .so file to detect if needs to be fixed or not

That would be idea if it can be made to work properly (Im not sure about the newer PE files)

If your going with a runtime now you would need to rebuild or use a script to strip the dylibs from the currently built wine versions.

**Comment by qparis** [comment]
Hmm not clear enough for me so far. I don't understand why the new format would break if runtime is not included directly. If you have any details, I'd be happy to understand more

**Comment by Gcenx** [comment]
> Hmm not clear enough for me so far. I don't understand why the new format would break if runtime is not included directly. If you have any details, I'd be happy to understand more

I'm not too sure on the why myself, if I use `fix_imports.sh` then use my own runtime winecfg gives mount error. Now if I skip `fix_imports.sh` then run winecfg on the new build doesn't give the mount error.
I actually get less error when not patching then when I patched the .so files, so it's safe to assume if `DYLD_FALLBACK_LIBRARY_PATH` is set with a runtime then wine functions correctly.

**Comment by qparis** [comment]
Ok, we need to investigate further with otool -L

**Comment by qparis** [comment]
A first step would be to isolate the libraries that are causing your bugs, and dump otool -L to both working and buggy version here. It would help a lot

**Comment by Gcenx** [comment]
I actually think we should first check over CrossOver's .so files as from memory they don't patch the .so files or even the dylib files.

So I'm wondering do we really need to patch these files? As before I never patched the .so files or dylibs files (just taken directly from macports)
I know it's recommended for most .app's but wine is not a stock apple.app.

**Comment by qparis** [comment]
AFAIK, it is required because we are cross compiling wine

**Comment by Gcenx** [comment]
> AFAIK, it is required because we are cross compiling wine

It would be nice if we can get it working properly.

All the thing I explained were done using a slightly modified version of this project (skipping fix_imports and not bundling dylib's)
So while patching the files would be correct it does function even if not patched

**Comment by Gcenx** [comment]
#92 That covers VKD3D building for amd64 runtime, both scripts updated to use PhoenicisRuntimeWinePackageCreator so runtime are placed in expected location instead of the base folder

**Comment by Gcenx** [comment]
> AFAIK, it is required because we are cross compiling wine

I've now tested Wine-4.9 back down to Wine-4.0 all built from Winebuild without patching the .so files and all are working normally.

All built without embedded dylibs instead using the runtime that was also created using Winebuild.
The dylibs did have `fix_imports.sh` ran on them and I don't see an error's in terminal about missing dylibs.

So I'm going with it's fine to skip patching the .so files but patching the dylibs should still be done so they can all find each other.
But that would mean Phoenicis needing to have the embedded runtime added.

**Comment by qparis** [comment]
Ok!
Phoenicis adds the runtime so we are fine here

**Comment by Gcenx** [comment]
I’ve changed my mind, keeping the runtime bundled with the wine package would hopefully keep an older package to still be functional long after it’s been built.

**Comment by Gcenx** [comment]
I’ve changed my mind, keeping the runtime bundled with the wine package would hopefully keep an older package to still be functional long after it’s been built.
