### ISSUE TITLE
Add default scripts

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis-winebuild#5]
We should have some default scripts for the most important use cases:
- build specific Wine version
- build all Wine versions

Both for Linux and OSX.

**Comment by qparis** [comment]
The first one already exists. 

For the second one, I’m wondering how it could be done. I think that we first need to solve the storage problem (I.e, be able to send the package somewhere once the build is generated). Then we shall build another component on top of that that will detect what builds are missing to build them

**Comment by qparis** [comment]
With fast enough servers we could also compile builds on-demand (and cache them)

**Comment by plata** [comment]
Ah, the first one is `interactive_builder` right? There should be a section in the README explaining the available scripts. I would also suggest to structure the scripts a bit more by adding subdirectories `scripts` and `examples`.
