### ISSUE TITLE
macOS Mojave - error on use after clean install

### ISSUE THREAD

**Issue by Gcenx** [PhoenicisOrg/phoenicis-winebuild#50]
I clean installed my Macbook Pro so I only have a single partition again since using this project means I don't need a High Sierra partition anymore.

Installed Docker.app from Docker.dmg
I again installed hombrew;
brew install python
pip3 install docker

And cloned the project using GitHub Desktop 
Here is the log using [GitHubGist](https://gist.github.com/Gcenx/e74350e4edbed715ec2eec0ffe423192)

I had the above error also before the reinstall but I planned to wipe my system anyway so I ignored it

**Comment by qparis** [comment]
Can you download the file? https://sdk.lunarg.com/sdk/download/1.1.92.1/mac/vulkansdk-macos-1.1.92.1.tar.gz

**Comment by Gcenx** [comment]
> We could grab it from macport. It just mean that we need to retest the build. Do you have any way to download the file with another IP adress? Then it will be cached locally and you won't have any problem

Yeah I can get it from another IP if anything I have my hotspot.
I feel dumb now :( 

For the moment I will just disable both MoltenVK and VKD3D on my end since I.m only compiling 32Bit for the moment.
I want to try fixing the missing dylib's problem, and that's forcing me to rebuild the container.

**Comment by qparis** [comment]
I see. When you make such tests, you can add your commands at the bottom of the Dockerfile. Then, the container won't be rebuilt
