### ISSUE TITLE
Gallium nine standalone

### ISSUE THREAD

**Issue by ImperatorS79** [PhoenicisOrg/phoenicis-winebuild#58]
By building it from here [https://github.com/dhewg/nine/]( https://github.com/dhewg/nine/), a verb for gallium nine can be made.

Seems it can be compiled with one Wine version and works on many others [https://github.com/dhewg/nine/issues/4](https://github.com/dhewg/nine/issues/4)

**Comment by qparis** [comment]
So what would you suggest? Just build the dll?

**Comment by ImperatorS79** [comment]
Their is a dll and a .exe (ninewinecfg). Their is tag in the repo for versions (0.1 atm).

**Comment by ImperatorS79** [comment]
For example
```
FROM amd64/debian:stretch

RUN echo 'deb-src http://deb.debian.org/debian stretch main' >> /etc/apt/sources.list
RUN echo 'deb-src http://security.debian.org/debian-security stretch/updates main' >> /etc/apt/sources.list
RUN echo 'deb-src http://deb.debian.org/debian stretch-updates main' >> /etc/apt/sources.list

RUN dpkg --add-architecture i386

RUN apt-get -y install meson pkg-config

RUN apt-get -y install libc6-dev libd3dadapter9-mesa-dev libx11-dev libx11-xcb-dev libxcb1-dev libxcb-dri3-dev libxcb-present-dev libxcb-xfixes0-dev libgl1-mesa-dev libegl1-mesa-dev

RUN apt-get -y install libc6-dev:i386 libd3dadapter9-mesa-dev:i386 libx11-dev:i386 libx11-xcb-dev:i386 libxcb1-dev:i386 libxcb-dri3-dev:i386 libxcb-present-dev:i386 libxcb-xfixes0-dev:i386 libgl1-mesa-dev:i386 libegl1-mesa-dev:i386

//wine-tools and libwine-dev, Install wine ? Recent wine version->one from phoenicis ? Is exporting PATH, LIBRARY_PATH, Include path working with meson  ?
```
and then to build:
```
git clone https://github.com/dhewg/nine.git
git checkcout v0.1

cd nine/
./release.sh
```

**Comment by ImperatorS79** [comment]
@qparis I have already compiled the file for 0.1 (only version currently), so maybe I could send it to you so that you already upload it on playonlinux.com., and then I try to write a verb for it.

**Comment by qparis** [comment]
Yes, anyway I will update winebuild to support this (and dxvk, and other stuff) probably before the end of the week.

**Comment by ImperatorS79** [comment]
Here it is [https://send.firefox.com/download/737dff35ad/#P-OTrCYLJp4miayu2KI_Gg](https://send.firefox.com/download/737dff35ad/#P-OTrCYLJp4miayu2KI_Gg).

**Comment by qparis** [comment]
Wine also provide binaries, it does not mean that we do not do winebuild :-)
