### ISSUE TITLE
New build script/option to import external wine source to compile?

### ISSUE THREAD

**Issue by Gcenx** [PhoenicisOrg/phoenicis-winebuild#65]
The idea is simple sometimes you might want to test out a modified wine-source but don't want to convert everything into patches to be used with the builder but instead want to just compile what you have without anything else.

- Import external wine-source
- Compile
- Compress & output build

**Comment by qparis** [comment]
You can do it with distribution.json :-)

**Comment by qparis** [comment]
Seems to be possible now. Can we close this ticket? :)

**Comment by Gcenx** [comment]
I'm not sure how that would be added since distributions.json wants to use a git repositry.

I was really saying copy in an external source from say $HOME/Desktop/WINESOURCE and compile that without using git release tags.

**Comment by qparis** [comment]
Well ok, in this case WineBuilder class needs to be split into two (or ideally three) parts, one that manage the source-fetching part (git cloning, fetching out the right version), and one that manage the source-patching/building part

**Comment by Gcenx** [comment]
I believe this was already implemented long ago so closing
