### ISSUE TITLE
Add Faudio to environment

### ISSUE THREAD

**Issue by ImperatorS79** [PhoenicisOrg/phoenicis-winebuild#69]
Wine 4.3 needs Faudio -> https://github.com/FNA-XNA/FAudio

**Comment by qparis** [comment]
Last merge request should fix it. (To be tested)

**Comment by qparis** [comment]
@ImperatorS79 The compiled lib does not seem to work:

root@a54c2bc98e42:~/faudio/build# gcc test.c -lSDL2 -lFAudio -L$PWD -I/usr/include/SDL2
//usr/local/lib/libFAudio.so: undefined reference to `SDL_atan2f'
//usr/local/lib/libFAudio.so: undefined reference to `SDL_HasNEON'
//usr/local/lib/libFAudio.so: undefined reference to `SDL_log10'
//usr/local/lib/libFAudio.so: undefined reference to `SDL_fabsf'
//usr/local/lib/libFAudio.so: undefined reference to `SDL_acosf'
//usr/local/lib/libFAudio.so: undefined reference to `SDL_exp'

Any idea?

**Comment by ImperatorS79** [comment]
I bet it is because the SDL2 version is too old. Maybe download the one from buster or sid.

**Comment by qparis** [comment]
Hum yep, but we needs to backport a lot more dependencies

**Comment by ImperatorS79** [comment]
I would assume some of those problems should be fixed by switching to buster when it comes out.

**Comment by qparis** [comment]
Fixed
