### ISSUE TITLE
Test that building of darwinx-x86 and darwin-amd64 works properly on linux

### ISSUE THREAD

**Issue by qparis** [PhoenicisOrg/phoenicis-winebuild#7]

**Comment by plata** [comment]
Should the builds be binary identical to the old build service? If so, we could just compare the results.

**Comment by qparis** [comment]
They are not. However, once they are built and the command “file wine” returns Mach-O, we could be confident that the build is working

**Comment by qparis** [comment]
By the way, the builds run great on MacOS. 
This is really cool because we could not build darwin64 version before
