### ISSUE TITLE
vcrun and dotnet verbs fail to install - macOS

### ISSUE THREAD

**Issue by Gcenx** [PhoenicisOrg/phoenicis-winebuild#71]
I discovered this issue when trying winetricks vcrun2010 as a required dependance.
This could be related to #45 as the same wine version from Winehq does not have that issue.

I tried it with and without quite mode and it stalls out when extracting.

**Comment by Gcenx** [comment]
The same also happens to any version of dotnet

**Comment by Gcenx** [comment]
Something on packages.macports is broken and that’s causing the above problems. This is not related to #45

I compiled wine on my Mac using XCode and a very small subset of dylibs and it’s able to install vcrun2010 without issue, didn’t try dotnet since it seems to be related to vcrun verbs not installing.

**Comment by Gcenx** [comment]
@qparis I partly tracked down the problem, something installed along with gnutls is causing these problems.

I can try to track down what's causing it, the other option would be compiling a mini version of Gnutls like what CrossOver uses.

**Comment by qparis** [comment]
Interesting. What do you prefer?

**Comment by Gcenx** [comment]
> Interesting. What do you prefer?

I'm thinking compiling Gnutls ourselves should be safer.
I remember seeing instructions before for compiling Gnutls only using gmp and the macos network framework but I didn't save the link.

**Comment by Gcenx** [comment]
> Interesting. What do you prefer?

@qparis I think compiling from source would be safer.
So we would need to compile
- gmp
- nettle
- gnutls

**Comment by Gcenx** [comment]
Resolved by #88
