### ISSUE TITLE
Request: Add more proton versions.

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/phoenicis-winebuild#72]
Proton has 32 releases (https://github.com/ValveSoftware/Proton/releases), but only one is present in phoenicis.

Ideally those should be present in phoenicis.

**Comment by ImperatorS79** [comment]
Superseded by #82

**Comment by Kreyren** [comment]
> Superseded by #82

Note that i requested **ALL** proton versions.. you are requesting only one

**Comment by ImperatorS79** [comment]
Nope, check the issue carefully.

**Comment by Kreyren** [comment]
Relevant: https://github.com/PhoenicisOrg/phoenicis/issues/1930
