### ISSUE TITLE
Wine 4.6 amd64 does not build on Linux

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis-winebuild#78]
see
- https://www.playonlinux.com/wine/logs/upstream-linux-amd64/PlayOnLinux-wine-4.6-upstream-linux-amd64.log
- https://www.playonlinux.com/wine/logs/staging-linux-amd64/PlayOnLinux-wine-4.6-staging-linux-amd64.log

Do we have an alert mechanism somewhere which notifies if something like this happens?

**Comment by Kreyren** [comment]
Note that https://github.com/PhoenicisOrg/phoenicis-winebuild/issues/79 is present on 4.5 staging

![image](https://user-images.githubusercontent.com/11302521/56565201-bf9a1200-65a7-11e9-865d-3834e3097989.png)

**Comment by plata** [comment]
@qparis I saw that you fixed this. Anything we should do about a notification mechanism? Otherwise I think this can be closed.

**Comment by Kreyren** [comment]
+1 to sanity check

**Comment by ImperatorS79** [comment]
I will close this and open a new issue about that.
