### ISSUE TITLE
Add support for Wine staging

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis-winebuild#8]

**Comment by qparis** [comment]
https://unix.stackexchange.com/questions/278423/how-to-enable-gtk-theming-wine-staging-in-playonlinux/482634#482634

**Comment by plata** [comment]
Can you upload the script which is finally used to build all Wine versions for Phoenicis (including staging) to this repo?

**Comment by qparis** [comment]
I will yep

**Comment by plata** [comment]
Ok. Feel free to close this once that's done.

**Comment by qparis** [comment]
Staging support is uploaded. Needs to be tested now

**Comment by plata** [comment]
Can you run it as a webservice already? If you give me the URL for the JSON, I can try it.

**Comment by qparis** [comment]
Not publicy yet, but I have successfully managed to replace the old system by this one last night. The engine is now catching up, espacially concerning OSX amd64/staging builds

**Comment by plata** [comment]
Ah ok. Somehow confusing nevertheless.
