### ISSUE TITLE
Missing Wine Proton 4.2 x64 (and other versions)

### ISSUE THREAD

**Issue by Zemogiter** [PhoenicisOrg/phoenicis-winebuild#82]
Based on comments in my reddit post (https://www.reddit.com/r/linux_gaming/comments/avhyxj/space_engineers_finally_playable_on_linux/?sort=new) we may need this version of Wine to get Space Engineers to work at all.

**Comment by ImperatorS79** [comment]
Phoenicis should provide at least Proton 4.2-3, 3.16-9,  4.2-2, 4.2-1 and 3.16-8

**Comment by qparis** [comment]
What are the corresponding branches?

**Comment by ImperatorS79** [comment]
Those are releases on https://github.com/ValveSoftware/Proton/releases.

**Comment by qparis** [comment]
Oh cool, they are finally using git tags. We are going to be able to automate proton builds

**Comment by Kreyren** [comment]
Relevant: https://github.com/PhoenicisOrg/phoenicis/issues/1930

**Comment by qparis** [comment]
> Oh cool, they are finally using git tags. We are going to be able to automate proton builds

Well they are not using git tags :( The repository proton has tags, but not ValveSoftware/Wine.
Therefore, we would need to read tag on proton, then get wine submodule commit and use it

**Comment by ferion11** [comment]
> Well they are not using git tags :( The repository proton has tags, but not ValveSoftware/Wine.
> Therefore, we would need to read tag on proton, then get wine submodule commit and use it

@qparis, I have made one clone of ValveSoftware/Wine and run "git tag", now. And, at this time, all tags are there.

By the way, the new wine5.3 (with big improvement like Full support for Unicode normalization), but the ["Wine building service"](https://www.playonlinux.com/wine/) don't show anything building.

**Comment by Zemogiter** [comment]
Closing due to lack of attention and the fact `Space Engineers` can run fine on upstream Wine.
