### ISSUE TITLE
OSXCROSS Updated - No longer building

### ISSUE THREAD

**Issue by Gcenx** [PhoenicisOrg/phoenicis-winebuild#93]
@qparis, I decided to wipe my docker images and re-download and build a clean copy of Winebuild.

However it seems some upstream changes have now broken our ability to build the project instead of locking the git cloning to a fixed working commit it would be better if possible to get it working, since it now support 10.13SDK, plus 10.14 and even the beta 10.15SDK that could come in handy later.

**Comment by Gcenx** [comment]
```
I added additinal packages I seen from someone else
git curl wget cmake clang llvm-dev libxml2-dev uuid-dev libssl-dev patch make tar xz-utils bzip2 gzip sed cpio libbz2-dev gcc g++ zlib1g-dev libmpc-dev libmpfr-dev  libgmp-dev
```

`RUN cd /root/osxcross && SDK_VERSION=10.11 OSX_VERSION_MIN=10.8 PORTABLE=true UNATTENDED=1 ./build.sh
`

I'm not too sure exactly what was needed from those changes but osxcross is building with thos changes.

**Comment by Gcenx** [comment]
Fixed

**Comment by qparis** [comment]
Thank you
