### ISSUE TITLE
Check why wine fails to load libgnutls

### ISSUE THREAD

**Issue by ImperatorS79** [PhoenicisOrg/phoenicis-winebuild#97]
One should check what `SONAME_LIBGNUTLS` wine expects in `wine/dlls/bcrypt/gnutls.c`.

**Comment by Gcenx** [comment]
You don't want to check that as all it cares about is checking gnutls on the host system.

You really need to check what gnutls requires to function, if a dependance is missing for gnutls it will fail to load and wine will just complain it can't load gnutls when really gnutls failed to load one of its dependencies.

**Comment by ImperatorS79** [comment]
Well wine is not really verbose about this. I have no idea which lib is missing, and when I install libgnutls30 from my system (instead of in the runtime) it still fails.

**Comment by Gcenx** [comment]
> Well wine is not really verbose about this. I have no idea which lib is missing, and when I install libgnutls30 from my system (instead of in the runtime) it still fails.

Ive had similar issues before with Gnutls being a complete pain, something else in the runtime could be causing a conflict with the native version causing it to fail I’ve had this exact issue. (On macOS but still same principle)

What’s the load order that’s being used? Does the runtime come before the system or after?

**Comment by ImperatorS79** [comment]
It should look like:
```
<path_to_runtime>:<path_to_wine_libs>:<ld_path>
```
the` ld_path` is empty before adding the runtime to it anyway.
