### ISSUE TITLE
Wine (staging) 4.12 and 4.12.1 missing

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis-winebuild#99]
only upstream x86 is complete

**Comment by Gcenx** [comment]
Skip 4.12 as it was bugged, only build 4.12.1

**Comment by qparis** [comment]
Containers are broken. I am repairing them

**Comment by qparis** [comment]
OSError: [Errno 28] No space left on device
This is why

**Comment by qparis** [comment]
Repaired https://www.playonlinux.com/wine/

**Comment by plata** [comment]
@qparis can you implement a mechanism to notify us in case the build didn't work?

**Comment by qparis** [comment]
Yes it could be done. However, it would require a little work to implement it.

**Comment by plata** [comment]
Is it still building? I'm missing:
- staging linux amd64: 4.13, 4.12.1
- upstream linux amd64: 4.13, 4.12.1
- upstream linux x86: 4.13

**Comment by qparis** [comment]
It is no longer building. I need to investigate to understand what can be happening

**Comment by plata** [comment]
Any news about this?

**Comment by qparis** [comment]
Apparently, winebuild tells me that they are built.. Are the archive missing?

**Comment by plata** [comment]
Not quite sure. At least I do not see them in Phoenicis (engines tab).

**Comment by ImperatorS79** [comment]
32 bits part of 64 bits build are not build due to lack of space:
https://www.playonlinux.com/wine/logs/staging-linux-amd64/PlayOnLinux-wine-4.12.1-staging-linux-amd64.log

It would be great if @qparis or anyone else could be automatically inform when there is new lacking dependencies (configure: lib* missing) or when the 32 bits part of a 64 bits wine is not build (which makes it unusable).

**Comment by qparis** [comment]
The lack of space has been fixed. 

I agree with your proposal. Feel free to give it a try

**Comment by ImperatorS79** [comment]
Then you should rebuild those one ^^. 4.12 and 4.12.1 at least.

**Comment by qparis** [comment]
They have already been rebuilt. The logs are concatenated

**Comment by ImperatorS79** [comment]
If the new log is appended to the old one, then they have been built without 32 bits support, check the link.

**Comment by plata** [comment]
Nobody should need these old versions anymore.
